export const ActionType = {
  // user action type
  UPDATE_USER_DATA: "UPDATE_USER_DATA",
  USER_SIGN_IN_FAIL: "USER_SIGN_IN_FAIL",
  USER_SIGNOUT: "USER_SIGNOUT",

  // category action type
  CATRGORY_INSERTED: "CATRGORY_INSERTED",
  CATRGORY_UPDATED: "CATRGORY_UPDATED",
  CATRGORY_DELETED: "CATRGORY_DELETED",
  CATEGORY_INSERT_FAIL: "CATEGORY_INSERT_FAIL",

  //product action type
  PRODUCT_ADD_SUCCESSFULLY: "PRODUCT_ADD_SUCCESSFULLY",
  PRODUCT_ADD_FAILED: "PRODUCT_ADD_FAILED",
  PRODUCT_UPDATED_SUCCESSFULLY: "PRODUCT_UPDATED_SUCCESSFULLY",
  PRODUCT_UPDATED_FAILED: "PRODUCT_UPDATED_FAILED",
  PRODUCT_DELECTED_SUCCESSFULLY: "PRODUCT_DELECTED_SUCCESSFULLY",
  ALL_PRODUCT_GETTING_SUCCESS : "ALL_PRODUCT_GETTING_SUCCESS",
  ALL_PRODUCT_GETTING_FAILED : "ALL_PRODUCT_GETTING_FAILED",
  
  //All category getter action type
  ALL_CATEGORY_GETTING_SUCCESS: "ALL_CATEGORY_GETTING_SUCCESS",
  ALL_CATEGORY_GETTING_FAILED: "ALL_CATEGORY_GETTING_FAILED",

  
};

